import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { mergeScene, toScene } from '../src/sceneSpec.js'
import { readTldrFile } from '../src/tldrFile.js'

// human-tweaked.tldr: 2-box scene where one box ("Original") was hand-refined
// in the "UI" to have rotation=0.3 and props.color='red'.
// Generated by: node scripts/gen-human-tweaked-fixture.mjs
const tweaked = readFileSync(new URL('./fixtures/human-tweaked.tldr', import.meta.url), 'utf8')

describe('mergeScene (merge-not-replace, grok HIGH)', () => {
  it('preserves hand-set rotation + color when editing a DIFFERENT field', () => {
    const { store } = readTldrFile(tweaked)

    // Find the record that was hand-tweaked (rotation === 0.3)
    const before = (store.allRecords() as any[]).find(
      (r) => r.typeName === 'shape' && r.rotation === 0.3,
    )
    expect(before).toBeTruthy()  // fixture sanity: the tweaked record must exist
    const editId = before.id

    // Edit ONLY the text of that box; rotation + color must survive
    mergeScene(store, {
      nodes: [{ id: editId, kind: 'box', text: 'EDITED', x: before.x, y: before.y }],
    })

    const after = (store.allRecords() as any[]).find((r) => r.id === editId)
    expect(after.rotation).toBe(0.3)        // preserved — merge-not-replace
    expect(after.props.color).toBe('red')   // preserved — merge-not-replace
    const { scene } = toScene(store)
    expect(scene.nodes.find((n) => n.id === editId)?.text).toBe('EDITED')  // changed
  })

  it('creates a new node when the id is not in the store', () => {
    const { store } = readTldrFile(tweaked)
    const countBefore = (store.allRecords() as any[]).filter(
      (r) => r.typeName === 'shape' && r.type === 'geo',
    ).length

    mergeScene(store, {
      nodes: [{ id: 'new-node', kind: 'box', text: 'Brand New', x: 0, y: 200 }],
    })

    const boxes = (store.allRecords() as any[]).filter(
      (r) => r.typeName === 'shape' && r.type === 'geo',
    )
    expect(boxes.length).toBe(countBefore + 1)
    const { scene } = toScene(store)
    expect(scene.nodes.some((n) => n.text === 'Brand New')).toBe(true)
  })
})
