/**
 * SceneSpec — high-level scene description → tldraw store records (Task 6).
 *
 * Create path only (Task 6). Merge path in Task 9. Edge records in Task 7.
 *
 * NEVER imports from 'tldraw' or '@tldraw/editor' — those hang Node.
 * All tldraw access goes through tldrawApi.ts only.
 * @tldraw/utils (reordering) is DOM-free and safe to import directly.
 */

import { makeStore, putRecord, getDefaultPropsFor, createShapeId, createBindingId, allRecords } from './tldrawApi.js'
import { toRich, toPlain } from './richtext.js'
import { getIndicesAbove, ZERO_INDEX_KEY } from '@tldraw/utils'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SceneSpec {
  title?: string
  nodes: SceneNode[]
  edges?: SceneEdge[]
}

export type SceneNode = BoxNode | NoteNode | TextNode

export interface BoxNode {
  id: string
  kind: 'box'
  shape?: string        // tldraw geo variant (rectangle, ellipse, etc.), default = rectangle
  text?: string
  x: number
  y: number
  w?: number
  h?: number
  color?: string
  fill?: string
  dash?: string
}

export interface NoteNode {
  id: string
  kind: 'note'
  text: string
  x: number
  y: number
  color?: string
}

export interface TextNode {
  id: string
  kind: 'text'
  text: string
  x: number
  y: number
  color?: string
  size?: string
}

export interface SceneEdge {
  from: string
  to: string
  text?: string
  arrowheadStart?: string
  arrowheadEnd?: string
  dash?: string
  color?: string
}

// ── Fractional index ──────────────────────────────────────────────────────────

/**
 * Returns a monotonic, lexicographically-sortable fractional index valid as a
 * tldraw IndexKey, generated by tldraw's own fractional-indexing library.
 *
 * Uses getIndicesAbove(null, n+1) to produce n+1 keys starting from the very
 * first valid slot, then returns the nth key. Guaranteed accepted by store.put
 * and lexicographically sorted (no "a10 < a2" string bug since tldraw's own
 * encoder handles ordering). Suitable for up to a few thousand siblings.
 *
 * n=0 → 'a1', n=1 → 'a2', …, n=9 → 'aA', n=10 → 'aB', … (base-62 integer part)
 */
export function indexAt(n: number): string {
  // Generate n+1 keys above null (i.e., from the start), return the nth
  return getIndicesAbove(null, n + 1)[n]
}

// ── Internal record builders ──────────────────────────────────────────────────

const PAGE_ID = 'page:page'

function buildShapeRecord(node: SceneNode, sid: string, index: string): Record<string, unknown> {
  const base = {
    id: sid,
    typeName: 'shape',
    x: node.x,
    y: node.y,
    rotation: 0,
    index,
    parentId: PAGE_ID,
    isLocked: false,
    opacity: 1,
    meta: {},
  }

  if (node.kind === 'box') {
    const p: any = { ...getDefaultPropsFor('geo'), richText: toRich(node.text ?? '') }
    if (node.shape != null) p.geo = node.shape
    if (node.w != null) p.w = node.w
    if (node.h != null) p.h = node.h
    if (node.color != null) p.color = node.color
    if (node.fill != null) p.fill = node.fill
    if (node.dash != null) p.dash = node.dash
    return { ...base, type: 'geo', props: p }
  }

  if (node.kind === 'note') {
    const p: any = { ...getDefaultPropsFor('note'), richText: toRich(node.text) }
    if (node.color != null) p.color = node.color
    return { ...base, type: 'note', props: p }
  }

  // text
  const p: any = { ...getDefaultPropsFor('text'), richText: toRich(node.text) }
  if (node.color != null) p.color = node.color
  if (node.size != null) p.size = node.size
  return { ...base, type: 'text', props: p }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Builds a tldraw store from a SceneSpec (create mode).
 *
 * Puts a document + page record, then one shape per node. Each `putRecord`
 * call validates against the tldraw schema — if a prop is wrong the store
 * throws immediately with the field name.
 *
 * The scene-id → shape-id map is stashed as `store.__idMap` (Map<string,string>)
 * so Task 7's edge builder can resolve arrow endpoints without re-scanning.
 *
 * @param scene   - The scene to create.
 * @param opts    - Pass `existing` to add nodes into an already-bootstrapped store
 *                  (used by Task 9 merge path); omit for a fresh store.
 */
export function fromScene(scene: SceneSpec, opts: { existing?: any } = {}): any {
  const store = opts.existing ?? makeStore()

  if (!opts.existing) {
    // Bootstrap the document root and the default page
    putRecord(store, {
      id: 'document:document',
      typeName: 'document',
      gridSize: 10,
      name: '',
      meta: {},
    })
    putRecord(store, {
      id: PAGE_ID,
      typeName: 'page',
      name: scene.title ?? 'Page 1',
      index: 'a1',
      meta: {},
    })
  }

  // scene-id → shape:id map; stashed for Task 7's edge builder
  const idMap = new Map<string, string>()

  scene.nodes.forEach((node, i) => {
    const sid = createShapeId()
    idMap.set(node.id, sid)
    putRecord(store, buildShapeRecord(node, sid, indexAt(i)))
  })

  // Stash on the store object for Task 7 (edges need endpoint shape ids)
  ;(store as any).__idMap = idMap

  // ── Edge loop (Task 7): each SceneEdge → one arrow shape + two binding records ──
  const edges = scene.edges ?? []
  edges.forEach((edge, j) => {
    const fromShapeId = idMap.get(edge.from)
    const toShapeId = idMap.get(edge.to)
    if (!fromShapeId || !toShapeId) {
      throw new Error(`edge references unknown node: ${edge.from} -> ${edge.to}`)
    }
    const arrowId = createShapeId()
    const props: any = { ...getDefaultPropsFor('arrow'), richText: toRich(edge.text ?? '') }
    if (edge.arrowheadStart != null) props.arrowheadStart = edge.arrowheadStart
    if (edge.arrowheadEnd != null) props.arrowheadEnd = edge.arrowheadEnd
    if (edge.dash != null) props.dash = edge.dash
    if (edge.color != null) props.color = edge.color
    putRecord(store, {
      id: arrowId,
      typeName: 'shape',
      type: 'arrow',
      x: 0,
      y: 0,
      rotation: 0,
      index: indexAt(scene.nodes.length + j),
      parentId: PAGE_ID,
      isLocked: false,
      opacity: 1,
      meta: {},
      props,
    })
    for (const [terminal, targetId] of [['start', fromShapeId], ['end', toShapeId]] as const) {
      putRecord(store, {
        id: createBindingId(),
        typeName: 'binding',
        type: 'arrow',
        fromId: arrowId,
        toId: targetId,
        meta: {},
        props: {
          terminal,
          normalizedAnchor: { x: 0.5, y: 0.5 },
          isPrecise: false,
          isExact: false,
          snap: 'none',
        },
      })
    }
  })

  return store
}

// ── Read path ─────────────────────────────────────────────────────────────────

/**
 * Converts a tldraw store back to a SceneSpec (read path).
 *
 * - geo shapes → BoxNode
 * - note shapes → NoteNode
 * - text shapes → TextNode
 * - arrow shapes + their two binding records → SceneEdge
 *   (binding.props.terminal==='start' → edge.from, 'end' → edge.to, both via toId)
 * - all other shape types → unmodeled list
 *
 * Returns `rawRecordsCount` as the total record count in the store (all typeName values).
 */
export function toScene(
  store: any,
): { scene: SceneSpec; unmodeled: { id: string; type: string }[]; rawRecordsCount: number } {
  const recs: any[] = allRecords(store)
  const rawRecordsCount = recs.length

  // Index shapes and bindings
  const shapes = recs.filter((r: any) => r.typeName === 'shape')
  const bindings = recs.filter((r: any) => r.typeName === 'binding')

  const nodes: SceneNode[] = []
  const unmodeled: { id: string; type: string }[] = []

  for (const r of shapes) {
    if (r.type === 'geo') {
      const node: BoxNode = {
        id: r.id,
        kind: 'box',
        text: toPlain(r.props.richText),
        x: r.x,
        y: r.y,
      }
      if (r.props.geo !== 'rectangle') node.shape = r.props.geo
      if (r.props.w != null) node.w = r.props.w
      if (r.props.h != null) node.h = r.props.h
      if (r.props.color != null) node.color = r.props.color
      if (r.props.fill != null && r.props.fill !== 'none') node.fill = r.props.fill
      if (r.props.dash != null) node.dash = r.props.dash
      nodes.push(node)
    } else if (r.type === 'note') {
      const node: NoteNode = {
        id: r.id,
        kind: 'note',
        text: toPlain(r.props.richText),
        x: r.x,
        y: r.y,
      }
      if (r.props.color != null) node.color = r.props.color
      nodes.push(node)
    } else if (r.type === 'text') {
      const node: TextNode = {
        id: r.id,
        kind: 'text',
        text: toPlain(r.props.richText),
        x: r.x,
        y: r.y,
      }
      if (r.props.color != null) node.color = r.props.color
      if (r.props.size != null) node.size = r.props.size
      nodes.push(node)
    } else if (r.type !== 'arrow') {
      unmodeled.push({ id: r.id, type: r.type })
    }
  }

  // Reconstruct edges: each arrow + its two bindings → one SceneEdge
  const arrowShapes = shapes.filter((r: any) => r.type === 'arrow')
  const edges: SceneEdge[] = []

  for (const arrow of arrowShapes) {
    const bs = bindings.filter((b: any) => b.fromId === arrow.id)
    const startBinding = bs.find((b: any) => b.props.terminal === 'start')
    const endBinding = bs.find((b: any) => b.props.terminal === 'end')
    if (startBinding && endBinding) {
      const edge: SceneEdge = {
        from: startBinding.toId,
        to: endBinding.toId,
      }
      const label = toPlain(arrow.props.richText)
      if (label) edge.text = label
      if (arrow.props.arrowheadStart != null) edge.arrowheadStart = arrow.props.arrowheadStart
      if (arrow.props.arrowheadEnd != null) edge.arrowheadEnd = arrow.props.arrowheadEnd
      if (arrow.props.dash != null) edge.dash = arrow.props.dash
      if (arrow.props.color != null) edge.color = arrow.props.color
      edges.push(edge)
    }
  }

  return { scene: { nodes, edges }, unmodeled, rawRecordsCount }
}
